version: '3.7'

services:
  web:
    build: ./english_phrasebook
    command: python manage.py runserver 0.0.0.0:8000
    volumes:
      - ./english_phrasebook/:/usr/src/english_phrasebook/
    ports:
      - 8000:8000
    env_file:
      - ./.env.dev
    depends_on:
      - db
  db:
    image: postgres:10.0-alpine
    volumes:
      - postgres_data:/var/lib/postgresql/data/
    environment:
      - POSTGRES_USER=phrasebook
      - POSTGRES_PASSWORD=phrasebook
      - POSTGRES_DB=phrasebook_dev

volumes:
  postgres_data: