# Generated by Django 3.0.8 on 2020-08-10 13:20

from django.db import migrations, models
import django.db.models.deletion
import phrasebook.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, unique=True, verbose_name='Name')),
                ('icon', models.ImageField(blank=True, null=True, upload_to=phrasebook.models.PathWithName('icons'), verbose_name='Icon file')),
            ],
        ),
        migrations.CreateModel(
            name='Level',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=2, unique=True, verbose_name="Level's code")),
                ('name', models.CharField(max_length=100, unique=True, verbose_name="Level's name")),
            ],
        ),
        migrations.CreateModel(
            name='Theme',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, unique=True, verbose_name="Theme's name")),
                ('photo', models.ImageField(blank=True, null=True, upload_to=phrasebook.models.PathWithName('photos'), verbose_name='Photo file')),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='phrasebook.Category', verbose_name="Category's name")),
                ('level', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='phrasebook.Level', verbose_name="Level's name")),
            ],
        ),
        migrations.CreateModel(
            name='Word',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, unique=True, verbose_name='Phrase')),
                ('translation', models.CharField(max_length=200, verbose_name='Translation')),
                ('example', models.CharField(blank=True, max_length=200, verbose_name='Usage example')),
                ('sound', models.FileField(blank=True, help_text='Allowed type - .mp3, .wav, .ogg', null=True, upload_to=phrasebook.models.PathWithName('sounds'), validators=[phrasebook.models.FileValidator(content_types=('audio/mpeg', 'audio/vnd.wave', 'audio/ogg'), max_size=52428800)], verbose_name='Sound file')),
                ('theme', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='words', to='phrasebook.Theme', verbose_name="Theme's name")),
            ],
        ),
    ]
