# Generated by Django 3.0.8 on 2020-07-30 13:33

from django.db import migrations, models
import django.db.models.deletion
import phrasebook.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, unique=True)),
                ('icon', models.ImageField(blank=True, null=True, upload_to=phrasebook.models.PathWithName('icons'))),
            ],
        ),
        migrations.CreateModel(
            name='Level',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=2, unique=True)),
                ('name', models.CharField(max_length=100, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='Theme',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, unique=True)),
                ('photo', models.ImageField(blank=True, null=True, upload_to=phrasebook.models.PathWithName('photos'))),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='phrasebook.Category')),
                ('level', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='phrasebook.Level')),
            ],
        ),
        migrations.CreateModel(
            name='Word',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, unique=True, verbose_name='phrase')),
                ('translation', models.CharField(max_length=200)),
                ('example', models.CharField(max_length=200)),
                ('sound', models.FileField(blank=True, help_text='Allowed type - .mp3, .wav, .ogg', null=True, upload_to=phrasebook.models.PathWithName('sounds'), validators=[phrasebook.models.FileValidator(content_types=('audio/mpeg', 'audio/vnd.wave', 'audio/ogg'), max_size=52428800)])),
                ('theme', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='words', to='phrasebook.Theme')),
            ],
        ),
    ]
