# Generated by Django 3.0.8 on 2020-07-31 07:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('phrasebook', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='category',
            options={'verbose_name': 'Category'},
        ),
    ]
