# Generated by Django 3.0.8 on 2020-07-31 09:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('phrasebook', '0002_auto_20200731_0740'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='category',
            options={'verbose_name': 'сategory', 'verbose_name_plural': 'categories'},
        ),
    ]
